### ISSUE TITLE
Cannot open JVM dynamic library

### ISSUE THREAD

**Issue by tjeffree** [perdian/macosappbundler-maven-plugin#43]
I've been using this plugin for some time to build my MacOS App. I may not have built it for a while (a year or so maybe) and now when attempting to run the built app I get this error:

```Cannot open JVM dynamic library at: /Users/xxx/Projects/xxx/target/xxx.app/Contents/Java/runtime/lib/libjli.dylib```

I've been experimenting with different configurations with the latest one below. Nothing appears to make a difference. The app runs fine in the IDE and using the built `jar`. The `dylib` is present and returns ok with `vtool`:

```
vtool -show-build /Users/xxx/Projects/xxx/target/xxx.app/Contents/Java/runtime/lib/libjli.dylib
/Users/xxx/Projects/xxx/target/xxx.app/Contents/Java/runtime/lib/libjli.dylib:
Load command 9
      cmd LC_BUILD_VERSION
  cmdsize 32
 platform MACOS
    minos 11.0
      sdk 11.1
   ntools 1
     tool LD
  version 609.8
```

Any help would be greatly appreciated, I'm running out of ideas of what might be causing it.

```
<plugin>
    <groupId>de.perdian.maven.plugins</groupId>
    <artifactId>macosappbundler-maven-plugin</artifactId>
    <version>1.19.0</version>
    <configuration>
        <plist>
            <CFBundleIconFile>src/main/resources/macos_icon.icns</CFBundleIconFile>
            <CFBundleDisplayName>xxx</CFBundleDisplayName>
            <CFBundleName>xxx</CFBundleName>
            <CFBundleDevelopmentRegion>English</CFBundleDevelopmentRegion>
            <JVMMainModuleName>xxx.xxx.xxx/xxx.xxx.xxx</JVMMainModuleName>
            <JVMVersion>17+</JVMVersion>
            <JVMOptions>
                <string>-Dapple.laf.useScreenMenuBar=true</string>
                <string>-Xdock:name=xxx</string>
            </JVMOptions>
            <JVMLogLevel>DEBUG</JVMLogLevel>
        </plist>
        <dmg>
            <generate>false</generate>
        </dmg>
        <jdk>
            <include>true</include>
            <location>/Library/Java/JavaVirtualMachines/jdk-17.0.2.jdk/Contents/Home</location>
        </jdk>
        <nativeBinary>X86_64</nativeBinary>
        <codesign>
            <identity>xxx (xxx)</identity>
        </codesign>
    </configuration>
    <executions>
        <execution>
            <phase>package</phase>
            <goals>
                <goal>bundle</goal>
            </goals>
        </execution>
    </executions>
</plugin>
```

MacOS info:

```
ProductName:		macOS
ProductVersion:		13.4
BuildVersion:		22F66
```

**Comment by jpage4500** [comment]
I'm also experiencing a similar issue - screenshot below - so I figured I'd just add to this one instead of create a new one.

1 difference in my case is I'm building the app on a M1 Mac and the resulting .app runs fine there. The issue happens when I try to run the same .app on an older X86 Intel Mac.

-- I'm not specifying anything for nativeBinary like the original post though. FWIW - I did try `<nativeBinary>X86_64</nativeBinary>` just to see if it'd run on the X86 Mac but I still got the same error
-- I wasn't specifying anything for `<jdk><location>` either but it didn't make a difference when I did

 @perdian - any ideas?
![image](https://github.com/perdian/macosappbundler-maven-plugin/assets/1895553/9bc231fb-3403-4d72-a77a-c87e7c9187e5)

My pom.xml is pretty minimal -- [link here](https://github.com/jpage4500/AndroidDeviceManager/blob/develop/pom.xml#L56)

I'm building on OS 13.1 (22C65) and running on OS 11.6.3 (20G415)

**Comment by perdian** [comment]
The screenshot and your description sound like you're **building** on an M1 Mac and **include** the JDK from that M1 Mac and you're **running** the application on an Intel Mac with the M1 JDK - which is a combination that might be problematic.

Could that be the reason?

**Comment by jpage4500** [comment]
>> sound like you're building on an M1 Mac and include the JDK from that M1 Mac and you're running the application on an Intel Mac with the M1 JDK - which is a combination that might be problematic

That sounds very reasonable.. but, does that mean I'm not able to build a mac app that runs on both platforms? At least one that includes the full JRE in it?

**Comment by perdian** [comment]
> does that mean I'm not able to build a mac app that runs on both platforms? At least one that includes the full JRE in it?

I think it works **one way**: If you include an x64 JRE that should be able to run on both architectures (on Mx via Rosetta) but the ARM JRE will **not** run on an x64 machine so no, I think your use case (bundling an ARM JRE and using that on both architectures) will not work.

**Comment by mattiacolombomc** [comment]
🚨 Hello @perdian , I really need your help here as this is some very urgent matter.

I think this is possibly a bug. I have tried to:

For case 1. and 2., I also manually checked if the JVM
1. Run on M3 Mac with a build from an Intel system with the default flag UNIVERSAL
2. Build on M3 Mac and run on M3 Mac, specifying `<nativeBinary>ARM_64</nativeBinary>` and INCLUDING the JDK
3. Build on M3 Mac and run on M3 Mac, specifying `<nativeBinary>ARM_64</nativeBinary>` and **NOT** INCLUDING the JDK

Maybe the plugin can't correctly include the library due to macOS sandboxing/security measures? Should I give the plugin higher privileges, someway?

_Please note: another member of my team is able to build and run on an Intel macOS device, so I'm sure this is not code-related._

[This](https://pastebin.com/eqyXJ9zJ) is our POM.


The result is always the same:
![CleanShot 2024-06-23 at 13 33 10@2x](https://github.com/perdian/macosappbundler-maven-plugin/assets/55593934/4c7adf59-101f-498e-99eb-cd0adae38c67)

![CleanShot 2024-06-23 at 13 37 03@2x](https://github.com/perdian/macosappbundler-maven-plugin/assets/55593934/f6653349-2db3-4601-8f48-ebfdbaa4fc53)

**Comment by perdian** [comment]
I don't have an Intel Mac available any longer so I cannot validate the setup.

What I **did** validate is that on Apple Silicon the builds works perfectly for a variety of scenarios:

1. Build and run the application **without** including a JDK.
2. Build and run the application **with** including the JDK from the **default** location (no dedicated `location` configuration)
3. Build and run the application **with** including the JDK from an **explicit** location (with dedicated `location` configuration)

I've tried all three options with both the `UNIVERSAL` as well as the `ARM_64` configured for the `nativeBinary` setting.

```
$ mvn --version
Apache Maven 3.9.8 (36645f6c9b5079805ea5009217e36f2cffd34256)
Maven home: /opt/homebrew/Cellar/maven/3.9.8/libexec
Java version: 22.0.1, vendor: Homebrew, runtime: /opt/homebrew/Cellar/openjdk/22.0.1/libexec/openjdk.jdk/Contents/Home
Default locale: de_DE, platform encoding: UTF-8
OS name: "mac os x", version: "14.5", arch: "aarch64", family: "mac"
```

Just to reiterate:
- If you build an application on an Apple Silicon machine **with a JDK included** then the JDK must also be an ARM_64 build of the JDK. The bundled application will **only** run on an Apple Silicon machine.
- If you build an application on an Apple Silicon machine **without a JDK included** and the `nativeBinary` is configured to `UNIVERSAL` then the bundled application should run on both Intel as well as Apple Silicon machines (though I cannot validate this as I don't have access to any Intel Macs any more).
- If you build an application on an Intel machine **with a JDK included** then the JDK must also be an AMD_64 build of the JDK. The bundled application will **only** run on an Intel machine.
- If you build an application on an Intel machine **without a JDK included** and the `nativeBinary` is configured to `UNIVERSAL` then the bundled application should run on both Intel as well as Apple Silicon machines (though I cannot validate this as I don't have access to any Intel Macs any more).
